### ISSUE TITLE
Improve Global Site Selector

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/globalsiteselector#60]
- [ ] [globalsiteselector/53](https://github.com/nextcloud/globalsiteselector/issues/53): Failure in user creation in Lookup Server in a Nextcloud Enterprise 22 instance
- [ ] [globalsiteselector/54](https://github.com/nextcloud/globalsiteselector/issues/54): Nextcloud 22: Global Site Selector cannot find the location of a valid user
- [ ] [globalsiteselector/55](https://github.com/nextcloud/globalsiteselector/issues/55): Cross-node share fails if gs.federation is set to its default value

Also notice that the combination of [server/29969](https://github.com/nextcloud/server/issues/29969) and [globalsiteselector/53](https://github.com/nextcloud/globalsiteselector/issues/53) makes Global Scale unusable in some way in the latest major Enterprise versions, 21 and 22.

**Comment by pmarini-nc** [comment]
https://github.com/nextcloud/globalsiteselector/issues/55 has been closed in favour of https://github.com/nextcloud/server/issues/14323
